#!/usr/bin/env bash

set -e 

COVERAGE_REPORT_ENGINE=${COVERAGE_REPORT_ENGINE:-"Llvm"}
COVERAGE_REPORT_OUTPUT_DIR=${COVERAGE_REPORT_OUTPUT_DIR:-"target/tarpaulin"}
COVERAGE_REPORT_OUTPUT_TYPE=${COVERAGE_REPORT_OUTPUT_TYPE:-"Html"}
COVERAGE_REPORT_REQUIRED_COVERAGE_PERCENTAGE=${COVERAGE_REPORT_REQUIRED_COVERAGE_PERCENTAGE:-90}

cargo tarpaulin --out "$COVERAGE_REPORT_OUTPUT_TYPE" --output-dir "$COVERAGE_REPORT_OUTPUT_DIR" --engine "$COVERAGE_REPORT_ENGINE" --fail-under "$COVERAGE_REPORT_REQUIRED_COVERAGE_PERCENTAGE"