name: Test project and create coverage report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests in debug mode
      run: cargo test --verbose
    - name: Run tests in release mode
      run: cargo test --verbose --release
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4
    - name: Install cargo-tarpaulin
      uses: taiki-e/install-action@v2
      with:
        tool: cargo-tarpaulin
    - name: Create coverage report, fail if coverage < 90%
      run: cargo tarpaulin --out Html --output-dir target/tarpaulin --engine Llvm --fail-under 90
    - name: Upload coverage report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: target/tarpaulin/
    - name: HTML Preview
      if: always()
      uses: pavi2410/html-preview-action@v4
      with:
        html_file: target/tarpaulin/tarpaulin-report.html
        job_summary: true